version: '2'
services:

  dynamodb:
    build: ./Dockerfiles/dynamodb
    volumes:
      - dynamodb-volume:/dynamo
    ports:
      - "8000:8000"

  lambda:
    build: ./Dockerfiles/lambda
    volumes:
      - ./mydoctransfer-lambda:/mydoctransfer-lambda
      - ~/.aws:/root/.aws
    ports:
      - "64123:8000"
    environment:
      - ENV=local
    depends_on:
      - dynamodb

volumes:
  dynamodb-volume: {}
