# Cognito
COGNITO_USER_POOL_NAME = 'CHANGE ME'
COGNITO_USER_POOL_ARN = 'CHANGE ME'
COGNITO_USER_POOL_ID = 'CHANGE ME'


# DynamoDB
DYNAMODB_FILE_TABLE_NAME = 'mydoctransfer-files'
DYNAMODB_AUDIT_TABLE_NAME = 'mydoctransfer-audit'


# S3
S3_UPLOADS_BUCKET_NAME = 'CHANGE ME'
